language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  # push coverage results to CodeCov
  - julia -e 'cd(Pkg.dir("Etcd")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # build documentation
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Etcd")); include(joinpath("docs", "make.jl"))'
